package com.zzg.dao;

import com.zzg.dingdan.povo.DingdanPovo;
import com.zzg.domain.Dingdan;
import com.zzg.domain.DingdanExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DingdanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int countByExample(DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int deleteByExample(DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int insert(Dingdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int insertSelective(Dingdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    List<Dingdan> selectByExample(DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    Dingdan selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") Dingdan record, @Param("example") DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int updateByExample(@Param("record") Dingdan record, @Param("example") DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int updateByPrimaryKeySelective(Dingdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 10:45:54 CST 2017
     */
    int updateByPrimaryKey(Dingdan record);


	List<DingdanPovo> selectdingdanbyuid(String uid);

	DingdanPovo selectbyoid(String oid);

	void updateStatus(Map<String, Object> map);

}